"""Type stubs for pyyudit."""

from __future__ import annotations

import os
from typing import NamedTuple

# Type aliases
StrPath = str | os.PathLike[str]
FontSource = bytes | bytearray | str | os.PathLike[str]

class GlyphRecord(NamedTuple):
    g: int
    cl: int
    dx: int
    dy: int
    ax: int
    ay: int
    flags: int

class TraceStage(NamedTuple):
    m: str
    glyphs: tuple[GlyphRecord, ...]
    depth: int
    effective: bool

class ShapedText(NamedTuple):
    glyphs: tuple[GlyphRecord, ...]
    advance_x: int
    advance_y: int
    text: str
    engine: str

class ShapedTrace(NamedTuple):
    stages: tuple[TraceStage, ...]
    final_glyphs: tuple[GlyphRecord, ...]
    advance_x: int
    advance_y: int
    text: str
    engine: str

class YuditError(Exception): ...
class LibraryNotFound(YuditError): ...
class FontError(YuditError): ...
class ShapingError(YuditError): ...

__version__: str
version_tuple: tuple[int, ...]

def configure(path: str | os.PathLike[str] | None = ...) -> None: ...
def is_available() -> bool: ...
def library_info() -> dict[str, object]: ...
def library_path() -> str | None: ...
def read_font_bytes(source: FontSource) -> bytes: ...
def upem_from_ttf(font_bytes: bytes) -> int: ...
def has_table(font_bytes: bytes, tag: str) -> bool: ...
def shape(font: FontSource, text: str, **kwargs: object) -> list[GlyphRecord]: ...
def shape_trace(font: FontSource, text: str, **kwargs: object) -> ShapedTrace: ...

class YuditFont:
    def __init__(self, data: bytes, *, face_index: int = ...) -> None: ...
    @classmethod
    def from_path(cls, path: StrPath) -> YuditFont: ...
    @classmethod
    def from_bytes(cls, data: bytes) -> YuditFont: ...
    def close(self) -> None: ...
    def __enter__(self) -> YuditFont: ...
    def __exit__(self, *exc: object) -> None: ...
    @property
    def upem(self) -> int: ...
    @property
    def glyph_count(self) -> int: ...
    @property
    def name(self) -> str: ...
    def shape(self, text: str) -> ShapedText: ...
    def shape_trace(self, text: str) -> ShapedTrace: ...
